--with table_xml as (
drop table if exists #table_xml;
select [codDataLoadRest], [datExecuted], cast([jsnResponse] as xml) as [jsnResponse]
into #table_xml
from [REP_DATALOAD_REST]
where [codDataLoadRest] = 142 and [dscHttpResponseCode] = 'OK';
--)

select [codDataLoadRest], 
r.value('(*:AltitudeMax)[1]','varchar(max)')               AS AltitudeMax,
r.value('(*:AltitudeMin)[1]','varchar(max)')               AS AltitudeMin,
r.value('(*:AnoCiclo)[1]','varchar(max)')                  AS AnoCiclo,
r.value('(*:AnoCicloRotacao)[1]','varchar(max)')           AS AnoCicloRotacao,
r.value('(*:AnoFinalPrevisto)[1]','varchar(max)')          AS AnoFinalPrevisto,
r.value('(*:AnoInicialPrevisto)[1]','varchar(max)')        AS AnoInicialPrevisto,
r.value('(*:AnoRotacao)[1]','varchar(max)')                AS AnoRotacao,
r.value('(*:AnodaFloresta)[1]','varchar(max)')             AS AnodaFloresta,
r.value('(*:AreaCortePredominante)[1]','varchar(max)')     AS AreaCortePredominante,
r.value('(*:AreaMaterialGenetico)[1]','varchar(max)')      AS AreaMaterialGenetico,
r.value('(*:AreaPlantada)[1]','varchar(max)')              AS AreaPlantada,
r.value('(*:AreaPrevista)[1]','varchar(max)')              AS AreaPrevista,
r.value('(*:AreaRotacao)[1]','varchar(max)')               AS AreaRotacao,
r.value('(*:AreaTalhao)[1]','varchar(max)')                AS AreaTalhao,
r.value('(*:AreaTalhaoMat)[1]','varchar(max)')             AS AreaTalhaoMat,
r.value('(*:AreaTalhaoMun)[1]','varchar(max)')             AS AreaTalhaoMun,
r.value('(*:AreaTalhaoSolo)[1]','varchar(max)')            AS AreaTalhaoSolo,
r.value('(*:Ciclo)[1]','varchar(max)')                     AS Ciclo,
r.value('(*:ClassePrecipitacao)[1]','varchar(max)')        AS ClassePrecipitacao,
r.value('(*:ClasseProdutividade)[1]','varchar(max)')       AS ClasseProdutividade,
r.value('(*:CodRegiao)[1]','varchar(max)')                 AS CodRegiao,
r.value('(*:DataFinalPrevista)[1]','varchar(max)')         AS DataFinalPrevista,
r.value('(*:DataFloresta)[1]','varchar(max)')              AS DataFloresta,
r.value('(*:DataImplantacao)[1]','varchar(max)')           AS DataImplantacao,
r.value('(*:DataInicialCiclo)[1]','varchar(max)')          AS DataInicialCiclo,
r.value('(*:DataInicialPrevista)[1]','varchar(max)')       AS DataInicialPrevista,
r.value('(*:DataInicialRotacao)[1]','varchar(max)')        AS DataInicialRotacao,
r.value('(*:DataPlantio)[1]','varchar(max)')               AS DataPlantio,
r.value('(*:DescricaoEspecie)[1]','varchar(max)')          AS DescricaoEspecie,
r.value('(*:DescricaoEstabelecimento)[1]','varchar(max)')  AS DescricaoEstabelecimento,
r.value('(*:DescricaoGenero)[1]','varchar(max)')           AS DescricaoGenero,
r.value('(*:DescricaoMaterialGenetico)[1]','varchar(max)') AS DescricaoMaterialGenetico,
r.value('(*:DescricaoMunicipio)[1]','varchar(max)')        AS DescricaoMunicipio,
r.value('(*:DescricaoProjeto)[1]','varchar(max)')          AS DescricaoProjeto,
r.value('(*:DescricaoRegiao)[1]','varchar(max)')           AS DescricaoRegiao,
r.value('(*:DescricaoSolo)[1]','varchar(max)')             AS DescricaoSolo,
r.value('(*:DescricaoUnidadeManejo)[1]','varchar(max)')    AS DescricaoUnidadeManejo,
r.value('(*:DescricaoUtilizacao)[1]','varchar(max)')       AS DescricaoUtilizacao,
r.value('(*:DescricaoVegetacao)[1]','varchar(max)')        AS DescricaoVegetacao,
r.value('(*:Distancia)[1]','varchar(max)')                 AS Distancia,
r.value('(*:EntreLinhas)[1]','varchar(max)')               AS EntreLinhas,
r.value('(*:EntrePlantas)[1]','varchar(max)')              AS EntrePlantas,
r.value('(*:Espacamento)[1]','varchar(max)')               AS Espacamento,
r.value('(*:EstacaoMeteorologica)[1]','varchar(max)')      AS EstacaoMeteorologica,
r.value('(*:IMA)[1]','varchar(max)')                       AS IMA,
r.value('(*:IdEstabelecimento)[1]','varchar(max)')         AS IdEstabelecimento,
r.value('(*:IdIntencaoManejo)[1]','varchar(max)')          AS IdIntencaoManejo,
r.value('(*:IdOrdemInvestPorRotacao)[1]','varchar(max)')   AS IdOrdemInvestPorRotacao,
r.value('(*:IdProjeto)[1]','varchar(max)')                 AS IdProjeto,
r.value('(*:IdRegionalProprietaria)[1]','varchar(max)')    AS IdRegionalProprietaria,
r.value('(*:IdTalhao)[1]','varchar(max)')                  AS IdTalhao,
r.value('(*:Idade)[1]','varchar(max)')                     AS Idade,
r.value('(*:IdentificadorGeo)[1]','varchar(max)')          AS IdentificadorGeo,
r.value('(*:Imovel)[1]','varchar(max)')                    AS Imovel,
r.value('(*:IntencaoManejo)[1]','varchar(max)')            AS IntencaoManejo,
r.value('(*:Latitude)[1]','varchar(max)')                  AS Latitude,
r.value('(*:Longitude)[1]','varchar(max)')                 AS Longitude,
r.value('(*:MaterialGeneticoPred)[1]','varchar(max)')      AS MaterialGeneticoPred,
r.value('(*:MatriculaPred)[1]','varchar(max)')             AS MatriculaPred,
r.value('(*:MunicipioPred)[1]','varchar(max)')             AS MunicipioPred,
r.value('(*:NumElementoCustoRotacao)[1]','varchar(max)')   AS NumElementoCustoRotacao,
r.value('(*:NumMatricula)[1]','varchar(max)')              AS NumMatricula,
r.value('(*:NumTalhao)[1]','varchar(max)')                 AS NumTalhao,
r.value('(*:OrdemDeInvestimento)[1]','varchar(max)')       AS OrdemDeInvestimento,
r.value('(*:Pais)[1]','varchar(max)')                      AS Pais,
r.value('(*:PeriodoReferencia)[1]','varchar(max)')         AS PeriodoReferencia,
r.value('(*:PorcentagemAreaImovel)[1]','varchar(max)')     AS PorcentagemAreaImovel,
r.value('(*:Regional)[1]','varchar(max)')                  AS Regional,
r.value('(*:Rotacao)[1]','varchar(max)')                   AS Rotacao,
r.value('(*:SiglaEspecie)[1]','varchar(max)')              AS SiglaEspecie,
r.value('(*:SiglaEstabelecimento)[1]','varchar(max)')      AS SiglaEstabelecimento,
r.value('(*:SiglaEstacaoMeteorologica)[1]','varchar(max)') AS SiglaEstacaoMeteorologica,
r.value('(*:SiglaEstado)[1]','varchar(max)')               AS SiglaEstado,
r.value('(*:SiglaGenero)[1]','varchar(max)')               AS SiglaGenero,
r.value('(*:SiglaIntencaoManejo)[1]','varchar(max)')       AS SiglaIntencaoManejo,
r.value('(*:SiglaProjeto)[1]','varchar(max)')              AS SiglaProjeto,
r.value('(*:SiglaRegiao)[1]','varchar(max)')               AS SiglaRegiao,
r.value('(*:SiglaTaxonomiaSolo)[1]','varchar(max)')        AS SiglaTaxonomiaSolo,
r.value('(*:SiglaUPC)[1]','varchar(max)')                  AS SiglaUPC,
r.value('(*:SiglaUnidadeManejoOper)[1]','varchar(max)')    AS SiglaUnidadeManejoOper,
r.value('(*:SiglaUtilizacao)[1]','varchar(max)')           AS SiglaUtilizacao,
r.value('(*:SiglaVegetacao)[1]','varchar(max)')            AS SiglaVegetacao,
r.value('(*:SituacaoFlorestal)[1]','varchar(max)')         AS SituacaoFlorestal,
r.value('(*:SoloPredominante)[1]','varchar(max)')          AS SoloPredominante,
r.value('(*:TipoElementoCusto)[1]','varchar(max)')         AS TipoElementoCusto,
r.value('(*:TipoIntervencao)[1]','varchar(max)')           AS TipoIntervencao,
r.value('(*:TipoPropriedade)[1]','varchar(max)')           AS TipoPropriedade,
r.value('(*:UPC)[1]','varchar(max)')                       AS UPC,
r.value('(*:UltimaAtualizacao)[1]','varchar(max)')         AS UltimaAtualizacao,
r.value('(*:UnidadeManejoOper)[1]','varchar(max)')         AS UnidadeManejoOper,
r.value('(*:Usuario)[1]','varchar(max)')                   AS Usuario,
r.value('(*:VolumeM3)[1]','varchar(max)')                  AS VolumeM3,
r.value('(*:VolumePorHa)[1]','varchar(max)')               AS VolumePorHa
from #table_xml t
cross apply t.[jsnResponse].nodes('/*:Envelope/*:Body/*:GetListaConsultaTalhaoResponse/*:GetListaConsultaTalhaoResult/*:List/*:Stand') AS A(r);