select 'Receita Bruta' as Conta, SUM(RECEITA_BRUTA_REAL) AS Valor, SK_ANO,SK_MES, COD_CC, NM_CC, FILIAL, REGIONAL, EMPRESA, ATIVIDADE, TECNOLOGIA, SEGMENTO,
       CLIENTE, ID_SYSPHERA,CENTRO_CUSTO_AREA_GERENCIA from [Stage].[Dbo].[STG_RECEITA]
where ATIVIDADE NOT LIKE '%PENALIDADE%' and ATIVIDADE NOT LIKE '%BONUS%'
group by SK_ANO,SK_MES, COD_CC, NM_CC, FILIAL, REGIONAL, EMPRESA, ATIVIDADE, TECNOLOGIA, SEGMENTO,CLIENTE, ID_SYSPHERA,CENTRO_CUSTO_AREA_GERENCIA
union all
select 'FI' as Conta, SUM(RECEITA_BRUTA_REAL) as Valor, SK_ANO,SK_MES, COD_CC, NM_CC, FILIAL, REGIONAL, EMPRESA, ATIVIDADE, TECNOLOGIA, SEGMENTO,
       CLIENTE, ID_SYSPHERA,CENTRO_CUSTO_AREA_GERENCIA from [Stage].[Dbo].[STG_RECEITA]
where ATIVIDADE LIKE '%BONUS%'
group by SK_ANO,SK_MES, COD_CC, NM_CC, FILIAL, REGIONAL, EMPRESA, ATIVIDADE, TECNOLOGIA, SEGMENTO, CLIENTE, ID_SYSPHERA,CENTRO_CUSTO_AREA_GERENCIA
union all
select 'Penalidade' as Conta, sum(RECEITA_BRUTA_REAL) AS Valor, SK_ANO,SK_MES, COD_CC, NM_CC, FILIAL, REGIONAL, EMPRESA, ATIVIDADE, TECNOLOGIA, SEGMENTO,
       CLIENTE, ID_SYSPHERA,CENTRO_CUSTO_AREA_GERENCIA from [Stage].[Dbo].[STG_RECEITA]
where ATIVIDADE LIKE '%PENALIDADE%'
group by SK_ANO,SK_MES, COD_CC, NM_CC, FILIAL, REGIONAL, EMPRESA, ATIVIDADE, TECNOLOGIA, SEGMENTO,
       CLIENTE, ID_SYSPHERA,CENTRO_CUSTO_AREA_GERENCIA
