update REP_PARAMETER set dscParameter = '' where  codParameter = 'AADClientId'
update REP_PARAMETER set dscParameter = '' where  codParameter = 'AADDomain'
update REP_PARAMETER set dscParameter = '' where  codParameter = 'AADTenantId'
update REP_PARAMETER set dscParameter = '' where  codParameter = 'AADUrlLogin'
update REP_PARAMETER set dscParameter = '' where  codParameter = 'AADUrlLogout'
update REP_PARAMETER set dscParameter = '' where  codParameter = 'ServiceProviderAuthenticationType'